spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /znalfxpt
  port: 8080

# 配置mybatis: (2)配置mapper文件, 设置配置文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml